STACK	SEGMENT	PARA	STACK	'STACK'
		DB	200	DUP(?)
STACK	ENDS
DATA	SEGMENT
SBCD1	DB	5, 6, 9, 2;2965
SBCD2	DB	2, 3, 7, 8;8732
SSUM	DB	5	DUP(0);５个字节去存储结果 算式为2965+8732=11697
CONT	DB	4
DATA	ENDS
CODE	SEGMENT
		ASSUME	CS:CODE, DS:DATA, SS:STACK, ES:DATA
SBCDAD:	MOV	AX,	DATA
		MOV	DS,	AX
		MOV	ES,	AX
		CLC
		CLD;DF=0 与LODSB操作有关，使LODSB后SI自动加1
		MOV	SI,	OFFSET	SBCD1
		MOV DI, OFFSET	SBCD2
		MOV	BX,	OFFSET	SSUM
		MOV	CL,	CONT
		MOV	CH,	0
		MOV AX, 0;AX清零
SBCDAD1:LODSB;把[SI]的数据送入AL，并使得SI++（DF=0）
		ADC	AL, [DI]
		AAA;对未压缩的BCD数之和做调整
		INC	DI
		MOV	BYTE PTR[BX], AL
		INC BX
		LOOP SBCDAD1
		MOV	BYTE PTR[BX], AL;把万位送给以SSUM为首地址的第五个顺序单元
		MOV	AH,	4CH
		INT	21H
CODE	ENDS
		END	SBCDAD