STACK	SEGMENT PARA STACK 'STACK'
		DB 100 DUP(?)
STACK	ENDS
DATA	SEGMENT
ADD1 	DB 0FEH, 86H, 7CH, 23H, 0A7H, 26H
ADD2	DB 0B3H, 73H, 11H, 9FH, 46H, 3EH
SUM		DB 6 DUP(0);算式为:26A7237C86FEH+3E469F1173B3H=64EDC28DFAB1H
CONT	DB 3
DATA	ENDS
CODE	SEGMENT
		ASSUME CS:CODE, SS:STACK, DS:DATA, ES:DATA
MADDB:	MOV AX, DATA
		MOV DS, AX
		MOV ES, AX
		MOV SI, OFFSET ADD1
		MOV DI, OFFSET ADD2
		MOV BX, OFFSET SUM
		MOV CL, BYTE PTR CONT
		MOV CH, 0
		CLC
MADDB1:	MOV AX, [SI]
		ADC AX, [DI]
		INC SI
		INC SI
		INC DI
		INC DI
		MOV [BX], AX
		INC BX
		INC BX
		LOOP MADDB1
		MOV AH, 4CH
		INT 21H
CODE	ENDS
		END MADDB